// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exxxqweozababiduwese.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4eHhxd2VvemFiYWJpZHV3ZXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTY5NTcsImV4cCI6MjA2ODc3Mjk1N30.diFwk3KVOePTN68whdJd7pp5B8MVhcp12oC4gjsk15Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});